In [29]:
import torch
randint=torch.randint(-100,100,(6,))
randint

tensor([ 83, -61,  67, -89,  14,  97])

In [ ]:
tensor=torch.tensor([[1,2],[3,4],[5,6]])
tensor

# directly getting the matrix of zeros of 2 rows and 3 columns
# zeros=torch.zeros(2,3)
zeros


tensor([[-4.0711e-28,  9.4868e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [10]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
input=torch.empty(2,3)
input

arange=torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [ ]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [20]:
logspace=torch.logspace(start=-10,end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [ ]:
eye=torch.eye(5)
eye #gives a matrix of 5*5

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [24]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
import time
import numpy as np


print("CUDA Available:", torch.cuda.is_available())
print("Torch Version:", torch.__version__)
print("Device Name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

block_size=8
batch_size=4

start_time=time.time()
# matrix operation here
zeros=torch.zeros(1,1)
end_time=time.time()


# As navdia is not supported in windows 11, so we are better using CPU instead if GPU
# Therefore it might take some time
elapsed_time=end_time-start_time
print(f"{elapsed_time:.8f}")


CUDA Available: False
Torch Version: 2.7.0+cpu
Device Name: No GPU
0.00000000


In [ ]:
with open('wizardLLM.txt','r',encoding='utf-8') as f:
    # for reading the file
    text=f.read()
    # for printing the 1st 200 texts
print(text[:200])

# now making a sorted array set for the characters
chars=sorted(set(text))
print(chars)
# printing the length of chars
print(len(chars))




ONLY A GIRL'S LOVE

by

CHARLES GARVICE







[Illustration]

New York
Street & Smith, Publishers

The S. & S. Novels Have No Rivals


STREET & SMITH, _Publishers_
NEW YORK


ONLY A GIRL'S LOVE.

['\n', ' ', '!', '"', '&', "'", '*', ',', '-', '.', '2', '4', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'æ', 'ê', '\ufeff']
72


In [ ]:
string_to_int={ch:i for i,ch in enumerate(chars)}
int_to_string={i:ch for i,ch in enumerate(chars)}
encode=lambda s:[string_to_int[c] for c in s]
decode=lambda l: ''.join([int_to_string[i] for i in l])

encoded_hello=encode('hello')
decoded_hello=decode(encoded_hello)
print(decoded_hello)

# more better approach for printing is using tensor
data=torch.tensor(encode(text),dtype=torch.long)
# printing the 1st 100 integers in the data
print(data[:100])

hello
tensor([71,  0,  0,  0, 29, 28, 26, 39,  1, 15,  1, 21, 23, 32, 26,  5, 33,  1,
        26, 29, 36, 19,  0,  0, 44, 67,  0,  0, 17, 22, 15, 32, 26, 19, 33,  1,
        21, 15, 32, 36, 23, 17, 19,  0,  0,  0,  0,  0,  0,  0,  0, 40, 23, 54,
        54, 63, 61, 62, 60, 43, 62, 51, 57, 56, 41,  0,  0, 28, 47, 65,  1, 39,
        57, 60, 53,  0, 33, 62, 60, 47, 47, 62,  1,  4,  1, 33, 55, 51, 62, 50,
         7,  1, 30, 63, 44, 54, 51, 61, 50, 47])


In [ ]:
# validation and training space
# EXAMPLE
n=int(0.8*len(data))
train_data=data[:n]
val_data=data[:n]
# training is 80% and last 20 % for validation, for the text corpus
# using training and validation splits


In [ ]:
# taking block size
block_size=8
x=train_data[:block_size]
y=train_data[1:block_size+1]

for t in range(block_size):
    context=x[t+1]
    target=y[t]
    print('when input is ',context,'target is', target)
    
